### ISSUE TITLE
Check namespaces before starting another test to avoid duplicates

### ISSUE THREAD

**Issue by jackzampolin** [jackzampolin/kube-integration-tests#1]
```Oct 11 00:09:14 kube-jump integrationtests[9794]: info: [master-1f76a31] comp: 289, remain: 7, iter: 56
Oct 11 00:09:43 kube-jump integrationtests[9794]: info: Post conatined following tags: master
Oct 11 00:09:43 kube-jump integrationtests[9794]: info: [master-5c64459] Starting...
Oct 11 00:09:44 kube-jump integrationtests[9794]: info: [master-5c64459] 296 queued...
Oct 11 00:10:09 kube-jump integrationtests[9794]: info: Post conatined following tags: latest
Oct 11 00:10:13 kube-jump integrationtests[9794]: info: [master-1f76a31] comp: 289, remain: 7, iter: 57
Oct 11 00:10:13 kube-jump integrationtests[9794]: info: [master-5c64459] 296 started...
Oct 11 00:10:44 kube-jump integrationtests[9794]: info: [master-5c64459] comp: 0, remain: 296, iter: 1
Oct 11 00:11:14 kube-jump integrationtests[9794]: info: [master-1f76a31] comp: 289, remain: 7, iter: 58
Oct 11 00:11:44 kube-jump integrationtests[9794]: info: [master-5c64459] comp: 0, remain: 296, iter: 2
Oct 11 00:12:13 kube-jump integrationtests[9794]: info: [master-1f76a31] comp: 289, remain: 7, iter: 59
Oct 11 00:12:44 kube-jump integrationtests[9794]: info: [master-5c64459] comp: 1, remain: 295, iter: 3
Oct 11 00:13:14 kube-jump integrationtests[9794]: info: [master-1f76a31] comp: 289, remain: 7, iter: 60
Oct 11 00:13:44 kube-jump integrationtests[9794]: info: [master-5c64459] comp: 3, remain: 293, iter: 4
Oct 11 00:14:13 kube-jump integrationtests[9794]: info: [master-1f76a31] comp: 289, remain: 7, iter: 61
Oct 11 00:14:44 kube-jump integrationtests[9794]: info: [master-5c64459] comp: 17, remain: 279, iter: 5
Oct 11 00:15:14 kube-jump integrationtests[9794]: info: [master-1f76a31] comp: 289, remain: 7, iter: 62
Oct 11 00:15:44 kube-jump integrationtests[9794]: info: [master-5c64459] comp: 32, remain: 264, iter: 6
Oct 11 00:16:14 kube-jump integrationtests[9794]: info: [master-1f76a31] comp: 289, remain: 7, iter: 63
Oct 11 00:16:44 kube-jump integrationtests[9794]: info: [master-5c64459] comp: 50, remain: 246, iter: 7
Oct 11 00:17:14 kube-jump integrationtests[9794]: info: [master-1f76a31] comp: 289, remain: 7, iter: 64
Oct 11 00:17:44 kube-jump integrationtests[9794]: info: [master-5c64459] comp: 63, remain: 233, iter: 8
Oct 11 00:18:14 kube-jump integrationtests[9794]: info: [master-1f76a31] comp: 289, remain: 7, iter: 65
Oct 11 00:18:44 kube-jump integrationtests[9794]: info: [master-5c64459] comp: 80, remain: 216, iter: 9
Oct 11 00:19:14 kube-jump integrationtests[9794]: info: [master-1f76a31] comp: 290, remain: 6, iter: 66
Oct 11 00:19:17 kube-jump integrationtests[9794]: info: Post conatined following tags: master
Oct 11 00:19:17 kube-jump integrationtests[9794]: info: [master-5c64459] Starting...
Oct 11 00:19:17 kube-jump integrationtests[9794]: info:  Error: namespaces "master-5c64459" already exists
Oct 11 00:19:17 kube-jump integrationtests[9794]:     at /home/ubuntu/kube-integration-tests/node_modules/kubernetes-client/lib/base.js:9:21
Oct 11 00:19:17 kube-jump integrationtests[9794]:     at Request.request [as _callback] (/home/ubuntu/kube-integration-tests/node_modules/kubernetes-client/lib/api-gr
Oct 11 00:19:17 kube-jump integrationtests[9794]:     at Request.self.callback (/home/ubuntu/kube-integration-tests/node_modules/request/request.js:186:22)
Oct 11 00:19:17 kube-jump integrationtests[9794]:     at emitTwo (events.js:125:13)
Oct 11 00:19:17 kube-jump integrationtests[9794]:     at Request.emit (events.js:213:7)
Oct 11 00:19:17 kube-jump integrationtests[9794]:     at Request.<anonymous> (/home/ubuntu/kube-integration-tests/node_modules/request/request.js:1163:10)
Oct 11 00:19:17 kube-jump integrationtests[9794]:     at emitOne (events.js:115:13)
Oct 11 00:19:17 kube-jump integrationtests[9794]:     at Request.emit (events.js:210:7)
Oct 11 00:19:17 kube-jump integrationtests[9794]:     at IncomingMessage.<anonymous> (/home/ubuntu/kube-integration-tests/node_modules/request/request.js:1085:12)
Oct 11 00:19:17 kube-jump integrationtests[9794]:     at Object.onceWrapper (events.js:314:30)
Oct 11 00:19:43 kube-jump integrationtests[9794]: info: Post conatined following tags: latest
Oct 11 00:19:44 kube-jump integrationtests[9794]: info: [master-5c64459] comp: 97, remain: 199, iter: 10
Oct 11 00:20:14 kube-jump integrationtests[9794]: info: [master-1f76a31] comp: 290, remain: 6, iter: 67
Oct 11 00:20:18 kube-jump integrationtests[9794]: info: [master-5c64459] comp: 98, remain: 198, iter: 1
Oct 11 00:20:44 kube-jump integrationtests[9794]: info: [master-5c64459] comp: 102, remain: 194, iter: 11
Oct 11 00:21:14 kube-jump integrationtests[9794]: info: [master-1f76a31] comp: 290, remain: 6, iter: 68
Oct 11 00:21:18 kube-jump integrationtests[9794]: info: [master-5c64459] comp: 103, remain: 193, iter: 2
Oct 11 00:21:44 kube-jump integrationtests[9794]: info: [master-5c64459] comp: 106, remain: 190, iter: 12
Oct 11 00:22:14 kube-jump integrationtests[9794]: info: [master-1f76a31] comp: 290, remain: 6, iter: 69
```

**Comment by jackzampolin** [comment]
Fixed!
